Music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mymusic.urls', namespace='mymusic')),
    path('', include('myuser.urls', namespace='myuser')),
    path('', include('user.urls', namespace='user')),
    path('', include('search.urls', namespace='search')),
    path('', include('play.urls', namespace='player')),
    path('', include('ranking.urls', namespace='ranking')),
    path('',include('label.urls',namespace='label')),
]

mymusic/urls.py
from django.urls import path


from mymusic.views import *
from myuser.views import home
from play.views import play
from ranking.views import rankingView
from search.views import search

app_name = 'mymusic'
urlpatterns = [
    path('index/', index, name='index'),
]

myuser/urls.py
from django.urls import path

from myuser.views import *

app_name = 'myuser'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('upload/',upload,name='upload'),
]

play/urls.py
from django.urls import path

from ranking.views import rankingView
from .views import play
app_name='play'

urlpatterns = [
    path('play/<song_id>/',play,name='play'),
]

ranking/urls.py
from django.contrib import admin
from django.urls import path, include

from mymusic.views import index
from play.views import play
from ranking.views import rankingView
from search.views import search
from user.views import user_home, logout

app_name = 'ranking'
urlpatterns = [
    path('ranking/', rankingView, name='ranking'),
    path('home/', user_home, name='home'),
    path('logout/', logout, name='logout'),
]

search/urls.py
from django.urls import path

from play.views import play
from ranking.views import rankingView
from search.views import search

app_name = 'search'

urlpatterns = [
    path('search/<int:page>/',search,name='search'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('home/', views.user_home,name='home'),
    path('logout/',views.logout,name='logout')
]

user/views.py
import os
import uuid

from django.shortcuts import render, redirect
from django.urls import reverse

from Music import settings
from myuser.views import upload

from mymusic.models import User


def user_home(request):
    user_id = request.session.get('user_id')
    if user_id:
        user = User.objects.get(pk=user_id)
        username = user.username
        figure_path = user.photo
    else:
        username = "点击登录"

    page = 1
    return render(request, 'home.html', locals())


def logout(request):
    request.session.flush()
    return redirect(reverse('mymusic:index'))

user/templates/home.html
{% extends "title_base.html"  %}

{% block title  %}
{% load staticfiles %}
<link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/user.css" %}">
</head>

<body class="member">
    <div class="header">
        <a href="/" class="logo" title="首页"><img src="{% static "image/logo.png" %}"></a>
        <div class="search-box">
            <form id="searchForm" action="{% url 'search:search' 1 %}" method="post" target="_blank">
            {% csrf_token %}
                <div class="search-keyword">
                <input id="kword" name="kword" type="text" class="keyword" maxlength="120" placeholder="音乐节"/>
                </div>
                <input id="subSerch" type="submit" class="search-button" value="搜 索" />
            </form>
            <div id="suggest" class="search-suggest"></div>
            <div class="search-hot-words">
                {% for song in search_song  %}
                    <a target="play" href="{% url 'player:play' song.song.song_id %}">{{ song.song.song_name }}</a>
                {% endfor  %}
            </div>
        </div>
    </div><!--end header-->

	<div class="nav-box">
		<div class="nav-box-inner">
			<ul class="nav clearfix">
				<li><a href="{% url 'mymusic:index' %}">首页</a></li>
				<li><a href="{% url 'ranking:ranking' %}" target="_self">歌曲排行</a></li>
	    	    <li><a href="{% url 'user:home' %}" target="_self">用户中心</a></li>
			</ul>
		</div>
	</div><!--end nav-box-->

    <div class="mod_profile js_user_data" style="">
        <div class="section_inner">
            <div class="profile__cover_link">
                <img src="{% static figure_path %}" class="profile__cover">
            </div>
            <h1 class="profile__tit">
                {% if request.session.user_id %}
                    <span class="profile__name">{{ user.username }}</span>
                {% else %}
                    <span class="profile__name"> <a href="{% url 'myuser:login' %}" style="color: red">点击登录</a> </span>
                {% endif %}
            </h1>
                <a href="{% url 'user:logout' %}" style="color:white;">退出登录</a>
        </div>
    </div>
	<div class="main main--profile" style="">
        <div class="mod_tab profile_nav" role="nav" id="nav">
            <span class="mod_tab__item mod_tab__current" id="hear_tab">我听过的歌</span>
        </div>
		<div class="js_box" style="display: block;">
			<div class="profile_cont">
				<div class="js_sub" style="display: block;">
					<div class="mod_songlist">
						<ul class="songlist__header">
							<li class="songlist__header_name">歌曲</li>
							<li class="songlist__header_author">歌手</li>
							<li class="songlist__header_time">时长</li>
						</ul>
						<ul class="songlist__list">
                            {% for item in contacts.object_list %}
							<li>
								<div class="songlist__item songlist__item--even">
							    <div class="songlist__songname">
                                    <a href="#" class="js_song songlist__songname_txt" >{{ item.song_name }}</a>
							    </div>
							    <div class="songlist__artist">
                                    <a href="javascript:" class="singer_name">{{ item.song_singer }}</a>
							    </div>
							    <div class="songlist__time">{{ item.song_time }}</div>
								</div>
							</li>
                            {% endfor %}
						</ul>
					</div><!--end mod_songlist-->

                    <!--分页-->
					<div class="page-box">
						<div class="pagebar" id="pageBar">

                            {% if contacts.has_previous %}
                            <a href="{% url 'user:home' contacts.previous_page_number %}" class="prev" target="_self"><i></i>上一页</a>
                            {% endif %}

                            {% for page in contacts.paginator.page_range %}
                                {% if contacts.number == page %}
                                    <span class="sel">{{ page }}</span>
                                {% else %}
                                    <a href="#" target="_self">{{ page }}</a>
                                {% endif %}
                            {% endfor %}

                            {% if contacts.has_next %}
                            <a href="#" class="next" target="_self">下一页<i></i></a>
                            {% endif %}

                        </div>
					</div>
				</div>
			</div>
		</div>
    </div><!-- end main -->

{% endblock  %}