Music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mymusic.urls', namespace='mymusic')),
    path('', include('myuser.urls', namespace='myuser')),
    path('', include('user.urls', namespace='user')),
    path('', include('search.urls', namespace='search')),
    path('', include('play.urls', namespace='player')),
    path('', include('ranking.urls', namespace='ranking')),
    path('',include('label.urls',namespace='label')),
]

mymusic/urls.py
from django.urls import path


from mymusic.views import *
from myuser.views import home
from play.views import play
from ranking.views import rankingView
from search.views import search

app_name = 'mymusic'
urlpatterns = [
    path('index/', index, name='index'),
]

play/urls.py
from django.urls import path

from ranking.views import rankingView
from .views import play
app_name='play'

urlpatterns = [
    path('play/<song_id>/',play,name='play'),
]

ranking/urls.py
from django.contrib import admin
from django.urls import path, include

from mymusic.views import index
from play.views import play
from ranking.views import rankingView
from search.views import search
from user.views import user_home, logout

app_name = 'ranking'
urlpatterns = [
    path('ranking/', rankingView, name='ranking'),
    path('home/', user_home, name='home'),
    path('logout/', logout, name='logout'),
]

search/urls.py
from django.urls import path

from play.views import play
from ranking.views import rankingView
from search.views import search

app_name = 'search'

urlpatterns = [
    path('search/<int:page>/',search,name='search'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('home/', views.user_home,name='home'),
    path('logout/',views.logout,name='logout')
]

play/views.py
from django.shortcuts import render

# Create your views here.
from mymusic.models import Songs, Singer


def play(request,song_id):
    song = Songs.objects.get(song_id=song_id)
    current_name=song.singer.singer_name
    play_list = Songs.objects.all()
    singer=Singer.objects.get(singer_name=current_name)
    song_relevant=singer.songs_set.all()

    return render(request,'play.html',locals())

play/templates/play.html
{% extends "title_base.html"  %}

{% block title  %}
{% load staticfiles %}
<link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/play.css" %}">
<style>

</style>
</head>
<body>
	<div class="header">
		<a href="#" class="logo" title="首页"><img src="{% static "image/logo.png" %}"></a>
		<div class="search-box">
			<!-- 歌曲查询 -->
            <form id="searchForm" action="{% url 'search:search' 1 %}" method="post" target="_blank">
            {% csrf_token %}
            <div class="search-keyword">
              <input id="kword" name="kword" type="text" class="keyword" maxlength="120" placeholder="请输入查询的内容"  />
            </div>
            <input id="subSerch" type="submit" class="search-button" value="搜 索" />
            </form>
            <div id="suggest" class="search-suggest"></div>
            <div class="search-hot-words">
                {% for song in search_song  %}
                <a target="play" href="{% url 'play' song.song.song_id %}" >{{ song.song.song_name }}</a>
                {% endfor  %}
            </div>
		</div>
	</div><!--end header-->
	<div class="nav-box">
		<div class="nav-box-inner">
			<ul class="nav clearfix">
				<li><a href="{% url 'mymusic:index' %}" style="color:white">首页</a></li>
{#                <li><a href=" {{ song.song_url }}">音乐</a></li>#}
				<li><a href="{% url 'ranking:ranking' %}" target="_self" style="color:white">歌曲排行</a></li>
	    	    <li><a href="{% url 'user:home' %}" target="_self" style="color:white">用户中心</a></li>
			</ul>
		</div>
	</div><!--end nav-box-->
	<!--后期修改-->
	<div class="wrapper clearfix">
        <div class="content">
            <div class="product-detail-box clearfix">
                <div class="product-pics"  >
                    <div class="music_box">

                        <div id="jquery_jplayer_1" class="jp-jplayer" data-url={{ song.song_url }}></div>
                        <div class="jp_img layz_load pic_po" title="点击播放"><img data-src={{ song.song_img }}></div>
                        <div id="jp_container_1" class="jp-audio">
                            <div class="jp-gui jp-interface">
                                <div class="jp-time-holder clearfix">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-time">
                                        <span class="jp-current-time" sty="color:white"></span> /
                                        <span class="jp-duration" sty="color:white"></span>
                                    </div>
                                </div>
                                <div class="song_error_corr" id="songCorr">
                                    <b class="err_btn" style="color:white">纠错</b>
                                    <ul>
                                        <li><span>歌词文本错误</span></li>
                                        <li><span>歌词时间错误</span></li>
                                        <li><span>歌曲错误</span></li>
                                    </ul>
                                </div>
                                <div class="jp-volume-bar">
                                    <div class="jp-volume-bar-value"></div>
                                </div>
                                <ul class="jp-controls clearfix">
                                    <li><a class="jp-play" tabindex="1" title="play"></a><a class="jp-pause" tabindex="1" title="pause"></a></li>
                                    <li><a class="jp-stop" tabindex="1" title="stop"></a></li>
                                    <li><a class="jp-repeat" tabindex="1" title="repeat"></a><a class="jp-repeat-off" tabindex="1" title="repeat off"></a></li>
                                    <li class="sound"><a class="jp-mute" tabindex="1" title="mute"></a><a class="jp-unmute" tabindex="1" title="unmute"></a></li>
                                </ul>
                            </div>
                        </div>
{#                        <div class="jplayer_content">#}
{#                            <ul id="lrc_list" class="lrc_list"></ul>#}
{#                        </div>#}
                    </div><!--end music_box-->
                    <textarea id="lrc_content" style="display:inline-block;height: 317px;width: 400px;color:white;text-align:center;background: transparent; border-style: none;font-size: 18px">{{ song.song_lyrics }}
                    </textarea>
                </div><!--end product-pics-->
                <div class="product-detail-main">
                    <div class="product-price">
                        <h1 id="currentSong" style="font-size: 40px;font-style:normal" align="left">{{ song.song_name }}</h1>
                        <div class="product-price-info" align="center">
                            <span style="color:white">歌手：{{ song.singer.singer_name }}</span>
                        </div>
                        <div class="product-price-info" align="center">
                            <span style="color:white">专辑：{{ song.song_album }}</span>
{#                            <span>语种：{{ song_info.song_languages }}</span>#}
                        </div>
                        <div class="product-price-info" align="center">
                            <span style="color:white">风格：{{ song.label.label_name }}</span>
{#                            <span>发行时间：{{ song_info.song_release }}</span>#}
                        </div>
                    </div><!--end product-price-->
                    <div class="product-comment">
                        <div class="links clearfix">
                            <a class="minimum-link-A click_down" href="#">下载</a>
                            <a class="minimum-link-A" href="#" >歌曲点评</a>
                        </div><!-- end links-->
                        <h3 class="list_title">当前播放列表</h3>
                        <ul class="playing-li" id="songlist">
                            <!--播放列表-->
                            {% for list in play_list %}
                            {%if list.song_id == song.song_id %}
                            <li data-id="{{list.song_id}}" class="current">
                            {%else %}
                            <li data-id="{{list.song_id}}">
                            {%endif %}
                            <span class="num" style="color:white">{{forloop.counter}}</span>
                            <a class="name" href="{% url 'player:play' list.song_id %}" target="play" style="color:white;font-size: 15px">{{list.song_name}}</a>
                            <a class="singer" href="javascript:;" target="_blank" style="color:white" >{{list.singer.singer_name}}</a>
                            </li>
                            {%endfor %}
                        </ul>
                        <div class="nplayL-btns" id="playleixin">
                        <ul>
                            <li class="order current" data-run="order">
                                <a class="icon" href="javascript:void(0)" title="顺序播放"></a>
                            </li>
                            <li class="single" data-run="single">
                                <a class="icon" title="单曲循环" href="javascript:void(0)"></a>
                            </li>
                            <li class="random" data-run="random">
                                <a class="icon" title="随机播放" href="javascript:void(0)"></a>
                            </li>
                            <li class="next" data-run="next">
                                <a href="{% url 'player:play' '7333'%}"><i></i>播放下一首</a>
                            </li>
                            </ul>
                        </div><!--end nplayL-btns-->
                    </div><!-- end product-comment -->
                </div><!-- end product-detail-main -->
            </div><!-- end product-detail-box -->

            <div class="section">
                <div class="section-header">
                    <h3>相关歌曲</h3>
                </div>
                <div class="section-content">
                    <div class="parts-box">
                        <a href="javascript:;" target="_self" id="J_PartsPrev" class="prev-btn"><i></i></a>
                        <div class="parts-slider" id="J_PartsList">
                            <div class="parts-list-wrap f_w">
                                <ul id="" class="parts-list clearfix f_s">
                                    {% for item in song_relevant %}
                                    <li>
                                        {% if item.song_id != song.song_id %}
                                        <a class="pic layz_load pic_po" href="{% url 'player:play' item.song_id %}" target="play" >
                                            <img data-src="{{ item.song_img }}">
                                        </a>
                                        <h4><a href="{% url 'player:play' item.song_id %}" target="play" style="color:white">{{ item.song_name}}</a></h4>
                                        <a href="javascript:;" class="J_MoreParts accessories-more" style="color:white">{{ item.singer.singer_name }}</a>
                                        {% endif %}
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <a href="javascript:;" target="_self" id="J_PartsNext" class="next-btn"><i></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

	<script data-main="{% static "js/play.js" %}" src="{% static "js/require.js" %}"></script>
{% endblock  %}