Music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mymusic.urls', namespace='mymusic')),
    path('', include('myuser.urls', namespace='myuser')),
    path('', include('user.urls', namespace='user')),
    path('', include('search.urls', namespace='search')),
    path('', include('play.urls', namespace='player')),
    path('', include('ranking.urls', namespace='ranking')),
    path('',include('label.urls',namespace='label')),
]

mymusic/urls.py
from django.urls import path


from mymusic.views import *
from myuser.views import home
from play.views import play
from ranking.views import rankingView
from search.views import search

app_name = 'mymusic'
urlpatterns = [
    path('index/', index, name='index'),
]

myuser/urls.py
from django.urls import path

from myuser.views import *

app_name = 'myuser'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('upload/',upload,name='upload'),
]

play/urls.py
from django.urls import path

from ranking.views import rankingView
from .views import play
app_name='play'

urlpatterns = [
    path('play/<song_id>/',play,name='play'),
]

myuser/forms.py
from django import forms

class UserRegister(forms.Form):
    username = forms.CharField(label='注册用户名',max_length=100)
    password1 = forms.CharField(label='设置密码',widget=forms.PasswordInput())
    password2 = forms.CharField(label='确认密码', widget=forms.PasswordInput())
    phone_num = forms.CharField(label='电话号码',max_length=15)

myuser/views.py
import hashlib
import os
import re
import uuid

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from Music import settings
from mymusic.models import User
from myuser.forms import UserRegister


def take_md5(content):
    md5 = hashlib.md5()  # 创建hash加密实例
    md5.update(content.encode())  # hash加密
    result = md5.hexdigest()  # 得到加密结果
    return result


def home(request):
    user_id = request.session.get('user_id')
    if user_id:
        user = User.objects.get(pk=user_id)
    return render(request, 'home.html', locals())


def register(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            name_filter = User.objects.filter(username=username)

            if len(name_filter) > 0:
                return render(request, 'register.html', {'error': '用户名已存在'})
            else:
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']

                if password1 != password2:
                    return render(request, 'register.html', {'error': '密码不一致！'})
                else:
                    password = take_md5(password1)
                    phone_num = form.cleaned_data['phone_num']
                    # print(type(phone_num))
                    rp = re.compile('(^[1][3-5|7-8][0-9]{9}$)')
                    if not rp.match(phone_num):
                        return render(request, 'register.html', {'error': '手机号码错误！'})
                    else:
                        photo = request.POST.get('photo')
                        user = User.objects.create(username=username, password=password, phone_num=phone_num,
                                                   photo=photo)
                        return redirect(reverse('myuser:login'))

    if request.method == 'GET':
        form = UserRegister()
        return render(request, 'register.html', locals())


@csrf_exempt  # 不会经过中间件
def upload(request):
    photoFile = request.FILES.get('photo')
    # 将上传的文件保存到/static/images/tmp目录中
    dir_ = os.path.join(settings.BASE_DIR, 'static/images/tmp')
    file_name = uuid.uuid4().hex + ('.jpg' if photoFile.content_type.endswith('jpeg') else '.png')
    with open(os.path.join(dir_, file_name), 'wb') as f:
        for chunk in photoFile.chunks():
            f.write(chunk)
    return JsonResponse({'msg': 1,
                         'path': f'images/tmp/{file_name}'})


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html', locals())

    if request.method == 'POST':
        username = request.POST.get('loginUser')
        password = request.POST.get('password')
        password1 = take_md5(password)
        # print(password1)
        users = User.objects.filter(username=username, password=password1)

        if users:
            user = users.first()
            request.session['user_id'] = user.id
            return redirect(reverse('user:home'))
        else:
            return render(request, 'login.html', {'error': '用户名或密码错误!'})

myuser/templates/home.html
{% extends "title_base.html"  %}
{% block title  %}
{% load staticfiles %}
<link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/user.css" %}">
</head>

<body class="member">
    <div class="header">
        <a href="/" class="logo" title="首页"><img src="{% static "image/logo.png" %}"></a>
        <div class="search-box">
            <form id="searchForm" action="#" method="post" target="_blank">
            {% csrf_token %}
                <div class="search-keyword">
                <input id="kword" name="kword" type="text" class="keyword" maxlength="120" placeholder="音乐节"/>
                </div>
                <input id="subSerch" type="submit" class="search-button" value="搜 索" />
            </form>
            <div id="suggest" class="search-suggest"></div>
            <div class="search-hot-words">
                {% for song in search_song  %}
                    <a target="play" href="#">{{ song.song.song_name }}</a>
                {% endfor  %}
            </div>
        </div>
    </div><!--end header-->

	<div class="nav-box">
		<div class="nav-box-inner">
			<ul class="nav clearfix">
				<li><a href="{% url 'mymusic:index' %}">首页</a></li>
				<li><a href="#" target="_blank">歌曲排行</a></li>
	    	    <li><a href="#" target="_blank">用户中心</a></li>
			</ul>
		</div>
	</div><!--end nav-box-->

    <div class="mod_profile js_user_data" style="">
        <div class="section_inner">
            <div class="profile__cover_link">
                <img src="{% static "image/user.jpg" %}" class="profile__cover">
            </div>
            <h1 class="profile__tit">
                <span class="profile__name">{{ user.username }}</span>
            </h1>
                <a href="#" style="color:white;">退出登录</a>
        </div>
    </div>

	<div class="main main--profile" style="">
        <div class="mod_tab profile_nav" role="nav" id="nav">
            <span class="mod_tab__item mod_tab__current" id="hear_tab">我听过的歌</span>
        </div>
		<div class="js_box" style="display: block;">
			<div class="profile_cont">
				<div class="js_sub" style="display: block;">
					<div class="mod_songlist">
						<ul class="songlist__header">
							<li class="songlist__header_name">歌曲</li>
							<li class="songlist__header_author">歌手</li>
							<li class="songlist__header_time">时长</li>
						</ul>
						<ul class="songlist__list">
                            {% for item in contacts.object_list %}
							<li>
								<div class="songlist__item songlist__item--even">
							    <div class="songlist__songname">
                                    <a href="#" class="js_song songlist__songname_txt" >{{ item.song_name }}</a>
							    </div>
							    <div class="songlist__artist">
                                    <a href="javascript:;" class="singer_name">{{ item.song_singer }}</a>
							    </div>
							    <div class="songlist__time">{{ item.song_time }}</div>
								</div>
							</li>
                            {% endfor %}
						</ul>
					</div><!--end mod_songlist-->

                    <!--分页-->
					<div class="page-box">
						<div class="pagebar" id="pageBar">

                            {% if contacts.has_previous %}
                            <a href="#" class="prev" target="_self"><i></i>上一页</a>
                            {% endif %}

                            {% for page in contacts.paginator.page_range %}
                                {% if contacts.number == page %}
                                    <span class="sel">{{ page }}</span>
                                {% else %}
                                    <a href="#" target="_self">{{ page }}</a>
                                {% endif %}
                            {% endfor %}

                            {% if contacts.has_next %}
                            <a href="#" class="next" target="_self">下一页<i></i></a>
                            {% endif %}

                        </div>
					</div>
				</div>
			</div>
		</div>
    </div><!-- end main -->

{% endblock  %}

myuser/templates/login.html
{% extends "title_base.html"  %}
{% block title  %}
{% load staticfiles %}
<link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/register.css" %}">
</head>

<body class="review">
<div class="wrapper">
    <div class="header clearfix">
        <a href="/" class="logo">我的音乐</a>
        <span class="logo-tip">Hi,我的音乐欢迎您!</span>
    </div>

    <div class="content clearfix">
        <!-- 登录版块 -->
        <div id="unauth_main" class="login-regist">
            <div class="login-box switch_box" style="display:block;">
                <div class="title">用户登录</div>
                <form id="loginForm" class="formBox" action="{% url 'myuser:login' %}" method="post">
                    {% csrf_token %}
                    <div id="loginForm" class="formBox">

                        <div class="itembox user-name">
                            <div class="item">
                                <input type="text" name="loginUser" placeholder="用户名" class="txt tabInput">
                            </div>
                        </div>
{#                        <div class="itembox user-pwd">#}
                            <div class="item">
                                <input type="password" name="password" placeholder="登录密码" class="txt tabInput">
                            </div>
                        {{ error }}
{#                        </div>#}
                        {% if tips %}
                            <div>提示:<span>{{ tips }}</span></div>
                        {% endif %}
                        <div id="loginBtnBox" class="login-btn">
                            <input id="J_LoginButton" type="submit" value="马上登录" class="tabInput pass-btn" />
                        </div>
                        <div class="pass-reglink">还没有我的音乐账号？<a class="switch" href="{% url 'myuser:register' %}">免费注册</a></div>
                    </div>
                </form>
            </div>
            <!-- //登录版块end -->
        </div>
    </div>
</div>
<script data-main="{% static "js/register.js" %}" src="{% static "js/require.js" %}"></script>
{% endblock  %}

myuser/templates/register.html
{% extends "title_base.html"  %}
{% block title  %}
{% load staticfiles %}
<link type="image/x-icon" rel="shortcut icon" href="{% static "favicon.ico" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/common.css" %}">
<link type="text/css" rel="stylesheet" href="{% static "css/register.css" %}">
</head>

<body class="review">
<div class="wrapper">
    <div class="header clearfix">
        <a href="/" class="logo">我的音乐</a>
        <span class="logo-tip">Hi,我的音乐欢迎您!</span>
    </div>
    <div class="content clearfix">
        <!-- 登录注册版块 -->
        <div id="unauth_main" class="login-regist">
            <!-- //登录版块end -->
            <div class="regist-box" style="display:inline-block;">
                <div class="title">用户注册</div>
                <form id="registerForm" class="formBox" method="post" action="">
                    {% csrf_token %}
                    <div id="registForm" class="formBox">
                    <div class="itembox user-name">
                        {{ form.as_p }}
                        {{ error }}
                    </div>
                    <div class="profile__cover_link">
                        <img src="{% static "image/user.jpg" %}"  width="100" height="100"
                    style="border: 1px solid red;padding: 5px;" id="preImg"  onclick="selector.click()">
                    </div>
                    <input type="hidden" name="photo" id="photo">
                    {% if tips %}
                        <div>提示:<span>{{ tips }}</span></div>
                    {% endif %}
                    <div class="member-pass clearfix">
                        <input id="agree" name="agree" checked="checked" type="checkbox" value="1"><label for="agree" class="autologon">已阅读并同意用户注册协议</label>
                    </div>
                        <input type="submit" value="免费注册" id="J_RegButton" class="pass-btn tabInput"/>
                        <div class="pass-reglink">已有我的音乐帐号，<a class="switch" href="{% url 'myuser:login' %}">立即登录</a></div>
                    </div>

                </form>
                <input type="file" id="selector" style="display: none" onchange="upload_img(this.files[0])">
            </div>
        </div>
    </div>
</div>
<script data-main="{% static "js/register.js" %}" src="{% static "js/require.js" %}"></script>
{% endblock  %}